version: "3"
services:
  ovrc:
    image: "ovrc:latest"
    container_name: "ovrc"
    ports:
      - "8002:8002"
      - "1234:1234"
    environment:
      - "OVRC_ENV=production"
      - "OVRC_WEB_PORT=:8002"
      - "OVRC_WEB_CERT_FILE=/dev_certs/ovrc.test+5.pem"
      - "OVRC_WEB_KEY_FILE=/dev_certs/ovrc.test+5-key.pem"
      - "OVRC_WEB_ALLOWED_ORIGINS=https://localhost:1234,http://localhost:1234,https://127.0.0.1:1234"
      - "OVRC_DB_CONNECTION=postgres://ovrc:ovrc@ovrc_db:5432/ovrc?sslmode=disable"
    links:
      - "postgresql:postgresql"
    depends_on:
      - postgresql
    #healthcheck:
    #  test: nc -z localhost 5432 # Check if postgres is up and running, doesn't seem to be needed for now?
    restart: always
    stdin_open: true  # Remove
    tty: true  # Remove
  postgresql:
    image: postgres:11
    container_name: "ovrc_db"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=ovrc"
      - "POSTGRES_PASSWORD=ovrc"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
