env = "development" # development|production

[webserver]
port = ":8002"
cert_file = "/Users/joao/ovrc/dev/certs/ovrc.test+5.pem"
key_file =  "/Users/joao/ovrc/dev/certs/ovrc.test+5-key.pem"
allowed_origins = ["https://localhost:1234", "http://localhost:1234", "https://127.0.0.1:1234"]